INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 14, in greet_user
    print(1/0)
ZeroDivisionError: division by zero
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 14, in greet_user
    print(1/0)
ZeroDivisionError: division by zero
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 14, in greet_user
    print(1/0)
ZeroDivisionError: division by zero
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 14, in greet_user
    print(1/0)
ZeroDivisionError: division by zero
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 20, in talk_to_me
    update.message.reply_text(text)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 20, in talk_to_me
    update.message.reply_text(text)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 20, in talk_to_me
    update.message.reply_text(text)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 20, in talk_to_me
    update.message.reply_text(text)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 22, in talk_to_me
    update.message.reply_text(text)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 22, in talk_to_me
    update.message.reply_text(text)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/bot.py", line 17, in greet_user
    update.message.reply_text('Hi, user!')
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/Users/margaritasmyslava/PycharmProjects/LP/projects/mybot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Bot have been started
INFO:apscheduler.scheduler:Scheduler started
